### ISSUE TITLE
Request for the pretrained model and instructions on getting own proteins' embeddings.

### ISSUE THREAD

**Issue by yunxiangz** [DeepGraphLearning/GearNet#11]
Thanks for the wonderful work!

I am trying the use the learned embeddings for a downstream protein classification problem on my own datasets. Since training the model requires a good HPC, I am wondering:
1. whether you could kindly upload your pretrained model.
2. could you explain how to generate the training and testing datasets (the pkl.gz file) from our own PDB files.
3. based on the generated pkl.gz file in Q1, how to apply the trained model to get the final embedding vectors (512 dimensions) for our own PDB files.

**Comment by Oxer11** [comment]
Hi! Thanks for raising these questions!

1.We have a plan for releasing model checkpoint, but it still takes some time for preparation. If it is urgent for you, you can send an email to me (zuobai.zhang@mila.quebec) and I'll personally share a (good but not ready) checkpoint with you.
2&3.To define a customized dataset, you can follow the tutorials in TorchDrug and TorchProtein. The [Customize Models & Tasks](https://torchdrug.ai/docs/notes/model.html) is about how to define a customized module in TorchDrug and [Tutorial 3-Structure-based Protein Property Prediction] is about how to define a dataset and run the GearNet model on it.

For your case, you can first define your customized dataset following the code of [`datasets.EnzymeCommission`](https://torchdrug.ai/docs/_modules/torchdrug/datasets/enzyme_commission.html#EnzymeCommission), which will show you how to generate .pkl.gz file with the API in TorchProtein. Then, you can load the task and model as the script in repo and then get the final embedding by calling `task.model()` (refer to [`tasks.MultipleBinaryClassification`](https://torchdrug.ai/docs/_modules/torchdrug/tasks/property_prediction.html#MultipleBinaryClassification)).

**Comment by yunxiangz** [comment]
Thank you Zuobai!
I have sent you a request email~
