### ISSUE TITLE
Dealing with proteins with multiple chains

### ISSUE THREAD

**Issue by dongli96** [DeepGraphLearning/GearNet#17]
For proteins with multiple chains, did you split them by chain and input the splits into the model one by one, or directly input the whole proteins?

In the section "F ADDITIONAL EXPERIMENTAL RESULTS ON EC AND GO PREDICTION - Pretraining on different datasets" of your paper, you wrote:

> Specifically, we extract 123,505
experimentally-determined protein structures from PDB whose resolutions are between 0.0 and 2.5
angstroms, **and we further extract 305,265 chains from these proteins to construct the final dataset**

which seems to implying that you trained the model on a bunch of single protein chains. However, meanwhile you did experiments of Enzyme Comission code prediction. To my knowledge, there are many enzymes containing more than one chain. It is impossible to split the enzyme into different chains and input into the model respectively (which hardly predicts the enzyme type correctly).

**Comment by Oxer11** [comment]
Yes, your understanding is correct. We pre-train our model on protein single-chain databases. The Enzyme Commission dataset is taken from DeepFRI paper (https://github.com/flatironinstitute/DeepFRI). This is constructed from [the SIFT database](https://www.ebi.ac.uk/pdbe/docs/sifts/index.html), which maps annotations to PDB chains. So all the proteins in the EC dataset is single-chain.

**Comment by dongli96** [comment]
Your explanation cleared up my confusion very well. Thank you.
