### ISSUE TITLE
Error in Fold3D config file

### ISSUE THREAD

**Issue by valegiunchiglia** [DeepGraphLearning/GearNet#21]
Hi! Thank you for your great work!! I just have a quick question. I am trying to use Gearnet with the Fold3D dataset using the configuration file you provided. But I keep on getting this error (I add the screenshot in attach). If I remove `mlp_batch_norm` and `mlp_dropout` the code runs, but the model doesn't seem to train properly. I would really appreciate if you could give me your input on that, or let me know what I am doing incorrectly.
Thanks a lot!!

![Screenshot 2023-04-04 at 14 51 18](https://user-images.githubusercontent.com/38138770/229814346-920f9a8e-c4ca-488d-b72a-3896de6b2000.png)

**Comment by Oxer11** [comment]
Hi, 

I've added a comment in README.md. To run Fold3D, you need to install the latest version of torchdrug from source. Sorry about the inconvenience! We'll update the latest version to conda and pip soon.

**Comment by valegiunchiglia** [comment]
Ahh!! That makes sense - I thought it might be a version issue, but I had the latest version from conda so I was not sure. Thanks for getting back to me so quickly!!
