### ISSUE TITLE
What information that the hidden dimensions respectively represent

### ISSUE THREAD

**Issue by BenardChase** [DeepGraphLearning/GearNet#28]
Hello! GearNet is really a good work! But I have a problem. I see that the hidden dimension set in the config file is [512,512,512,512,512,512]. Since I don't know much about the specific principle of graph neural network, I want to know what information these dimensions respectively represent.Thank you!

**Comment by Oxer11** [comment]
Hi, thanks for your question! These denote the hidden dimensions of the graph neural network, which means the network will have six hidden layer with 512 dimensional representations. You can find the detailed description in the [doc](https://torchdrug.ai/docs/api/models.html#gearnet).

**Comment by BenardChase** [comment]
Thank you for your kind reply.But in the GearNet instance mentioned in another document, the  hidden dimensions were only set as [512, 512, 512]. I would like to know what the difference between them.

**Comment by Oxer11** [comment]
The tutorial you refer to is only for illustration, so we only use a shallow graph neural network to run on colab. In practice, we need at least 6 layers to get good performance.
