### ISSUE TITLE
Any plans on releasing the model's weights?

### ISSUE THREAD

**Issue by crochereau** [DeepGraphLearning/GearNet#3]
Hi, 
Thank you for your great work. Do you plan on releasing the model's weights any time soon? The README doesn't seem to mention any pretrained model. This would be very helpful to quickly get representations for new sequences.

**Comment by huzongxiang** [comment]
> Hi!
> 
> Thanks for the nice words! We're going to release the model weights in the next few months.

Looking forward to the release !

**Comment by pjsample** [comment]
Hello, are there any updates on releasing the model weights? Specifically the pretrained models. I'm attempting to train it myself but downloading and processing the files from Alphafold is really slow.

Thanks.

**Comment by Oxer11** [comment]
Sorry for the late reply. You can check the latest README. I've updated the link to pre-trained models last week.

**Comment by pjsample** [comment]
Thank you!
