### ISSUE TITLE
Training details of basic GearNet on Fold prediction task

### ISSUE THREAD

**Issue by YanjingLiLi** [DeepGraphLearning/GearNet#31]
Hi, may I ask if you can provide your training details of basic GearNet (without IEConv) on the Fold prediction task? 
The results of your paper are in page 8:
`28.4 42.6 95.3` for `test_fold, test_superfamily, test_family`.

Is it here `https://github.com/DeepGraphLearning/GearNet/blob/main/config/downstream/Fold3D/gearnet.yaml`? I didn't find the basic GearNet model architecture in this repo.

Thanks!

**Comment by Oxer11** [comment]
Hi, you're right. [This](https://github.com/DeepGraphLearning/GearNet/blob/main/config/downstream/Fold3D/gearnet.yaml) is the config for running GearNet on Fold3D. In this config, we turn off the `use_ieconv` option to use a vanilla GearNet.

**Comment by YanjingLiLi** [comment]
Thanks! Did you finally use an additional linear layer to convert the graph representation as the output of the model into 1195 (num_classes) classes?

**Comment by Oxer11** [comment]
Yes, I use a 3-layer MLP for prediction as defined [here](https://github.com/DeepGraphLearning/GearNet/blob/1a1d15dcba393f47d18d18e2e945b895c3a848fa/config/downstream/Fold3D/gearnet.yaml#L13). You can find the implementation in [`torchdrug.tasks.PropertyPrediction`](https://github.com/DeepGraphLearning/torchdrug/blob/master/torchdrug/tasks/property_prediction.py).

**Comment by YanjingLiLi** [comment]
I want to reproduce your work using ```python script/downstream.py -c config/downstream/Fold3D/gearnet.yaml --gpus [0]```, but it returns an error:

```Traceback (most recent call last):
  File "script/downstream.py", line 17, in <module>
    from gearnet import dataset, model
  File "/lustre07/scratch/liusheng/GearNet/GearNet_test/GearNet/gearnet/dataset.py", line 17, in <module>
    class Fold3D(data.ProteinDataset):
AttributeError: module 'torchdrug.data' has no attribute 'ProteinDataset'
```

I believe I have torchdrug installed.

**Comment by Oxer11** [comment]
Hi, could you provide the version of your torchdrug? For Fold3D, you need to install torchdrug from source.

**Comment by YanjingLiLi** [comment]
Get it. I used git clone to clone the torchdrug repo. 

By the way, how did you train your GearNet_IEConv with hidden size [512, 512, 512, 512, 512, 512] as described in your config? I always encountered the "cuda out of memory error".

**Comment by Oxer11** [comment]
I use 40GB A100 for training. If you don't have large enough gpu memory, maybe consider a smaller batch size or smaller mdoel.
