### ISSUE TITLE
Attribution information of the Fold3D dataset

### ISSUE THREAD

**Issue by YanjingLiLi** [DeepGraphLearning/GearNet#32]
Hi, may I ask if you have a more detailed description of the data structure of the protein `.hdf5` file of the Fold3D dataset? I find it contains much information about the protein, but I am not sure what some of them mean.

**Comment by YanjingLiLi** [comment]
Specifically, what do `cov_bond_list_hb` and `cov_bond_list_sindices_hb` mean?

**Comment by Oxer11** [comment]
Hi, this is directly taken from IEConv's implementation, so I also don't know about the meanings of some keys.
