### ISSUE TITLE
a question about the downstream tasks

### ISSUE THREAD

**Issue by onlyonewater** [DeepGraphLearning/GearNet#38]
hi, authors, great works, I notice that the GearNet does 4 downstream tasks, they are 1): EC number prediction, 2): GO term prediction, 3): Fold classification, 4): Reaction classification, I am interested in the GO term prediction task, could the authors release the corresponding dataset about this task? Thanks!!!

**Comment by Oxer11** [comment]
Hi, thanks for the good words. I actually have released the dataset [here](https://torchdrug.ai/docs/_modules/torchdrug/datasets/gene_ontology.html#GeneOntology), which can be downloaed from [zenodo](https://zenodo.org/record/6622158/) directly.
