### ISSUE TITLE
Edge_list set to [0,0,0]

### ISSUE THREAD

**Issue by andrew7shen** [DeepGraphLearning/GearNet#40]
Hi, thanks for your work!

In the Fold3D dataset class, why is the edge_list field set to an empty edge list of [[0,0,0]] when the input hdf5 files are loaded (on line 85 in dataset.py)? I'm trying to load in my own protein graphs into the GearNetIEConv model to get an output embedding, and if I don't set edge_list=[[0,0,0]], I run into an IndexOutOfBounds error later on when the protein graph is getting passed through the "message" function of the GeometricRelationalGraphConv layer.

**Comment by Oxer11** [comment]
Hi, we need to set a placeholder for `edge_list` when loading the protein and the real edges are constructed during the model forward process.

**Comment by andrew7shen** [comment]
Makes sense, thanks!
