### ISSUE TITLE
secondary structure evaluation

### ISSUE THREAD

**Issue by ejko99** [DeepGraphLearning/GearNet#50]
Hi, thank you for your amazing work!

I am trying to evaluate GearNet on secondary structure dataset, but it gives me this error:

AttributeError: 'PackedProtein' object has no attribute 'node_position'

I think it is because secondary structure datset doesn't provide node_position, which is needed for gearnet.

Is there any other way I can evaluate secondary structure on gearnet?

Thank you.

**Comment by Oxer11** [comment]
Hi, thanks for the question.

The problem setting is questionable. Secondary structure prediction is defined as a sequence-only task, while GearNet is designed as a structure encoder to learn protein representations, which requires protein structures as input. So you cannot use GearNet to predict the secondary structure without structures as input. On the other hand, if you already know the structure of the protein, then you know about the secondary structure and don't need GearNet for prediction.

**Comment by ejko99** [comment]
Thank you for your kind reply!
I guess I was mistaken. Thanks!
