### ISSUE TITLE
input data

### ISSUE THREAD

**Issue by hxu105** [DeepGraphLearning/GearNet#8]
Dear authors, thanks for your great works.
I have some questions about the data. I try to visualize the input protein sequence by call the to_sequence() during each batch. Here is the figure showing the sequence.
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/40327643/200474535-d58cd037-25ff-463b-9f7a-99129f1bfc0b.png">
I wonder why there are some many .Gs, since . is a separator for multiple sequences (https://github.com/DeepGraphLearning/torchdrug/issues/151). Also, after deleting all the ., the length of remaining sequence is the same as the number of the graph's nodes. Could you help to explain why there are some many .Gs? Many thanks!

**Comment by Oxer11** [comment]
Hi, thanks for raising this question! I guess this can be explained as follows.

First, when loading a protein from a pdb file with TorchProtein, the unknown residue types will be recognized as glycines (see [this](https://torchdrug.ai/docs/_modules/torchdrug/data/protein.html#Protein.from_molecule)). Then, when using the `data.Protein.to_sequence()` to output the sequence (see [this](https://torchdrug.ai/docs/_modules/torchdrug/data/protein.html#Protein.to_sequence)), different connected components are seperated by dots. 

The pdb file shown in your figure may contain many HETATM in the end, which cannot be recognized and thus are treated as GLY without links to other residues. These atoms will be discarded when you run residue-level model with the graph construction model (see [this](https://torchdrug.ai/docs/_modules/torchdrug/layers/geometry/function.html#AlphaCarbonNode)).
