### ISSUE TITLE
About The Pre-training Process

### ISSUE THREAD

**Issue by Mrz-zz** [DeepGraphLearning/GearNet#9]
Hey, I am sorry to trouble you about the pre-training details about GeatNet. :)

After pre-training on the AlphaFold, will you fix the model's parameters and only change the prediction head's parameter? Or update the pre-trained model and its corresponding prediction head together?

**Comment by Oxer11** [comment]
Hi! After pretraining, we finetune both the model and prediction head together. You can simply finetune the model with the same config file by passing the checkpoint in the argument.

**Comment by Mrz-zz** [comment]
Ok, I will try to fine-tune the model based on your suggestions. Best wishes!
